# Netlify config para rotas limpas e SPA est√°tica
[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/recursos"
  to = "/recursos.html"
  status = 200

[[redirects]]
  from = "/privacidade"
  to = "/privacidade.html"
  status = 200

[[redirects]]
  from = "/obrigado"
  to = "/obrigado.html"
  status = 200
